[WIP] Init AMQP k6 plugin
grafana/xk6-amqp pull request #1
Opened 2021-07-14 15:43 UTC by lxkuz

2021-07-21 10:46 UTC, simskij requested changes
Minor feedback items. All in all; looks good. 👏🏽

2021-07-21 10:46 UTC, simskij commented on README.md
> +> Any issues with the tool should be raised [here](https://github.com/k6io/xk6-amqp/issues).
```suggestion
> Any issues with the tool should be raised [here](https://github.com/grafana/xk6-amqp/issues).
```

2021-07-21 10:46 UTC, simskij commented on README.md
> +  $ xk6 build --with github.com/k6io/xk6-amqp@latest
```suggestion
  $ xk6 build --with github.com/grafana/xk6-amqp@latest
```

2021-07-21 10:46 UTC, simskij commented on amqp.go
> +	modules.Register("k6/x/amqp/exchanges", &exchanges)
```suggestion
	modules.Register("k6/x/amqp/queue", &queues)
	modules.Register("k6/x/amqp/exchange", &exchanges)
```

Use singularis throughout unless the pluralization adds semantic value.

2021-07-21 10:46 UTC, simskij commented on exchanges.go
> +type EchangeDeclareOptions struct {
```suggestion
type ExchangeDeclareOptions struct {
```

2021-07-21 13:54 UTC, lxkuz commented on README.md
> +> Any issues with the tool should be raised [here](https://github.com/k6io/xk6-amqp/issues).
@simskij does it mean I should use `github.com/grafana` instead of `github.com/k6io` **everywhere**?

2021-07-21 14:00 UTC, lxkuz commented
@simskij review comments handled

2021-07-23 12:16 UTC, simskij commented on README.md
> +> Any issues with the tool should be raised [here](https://github.com/k6io/xk6-amqp/issues).
Yes, correct

2021-07-23 12:19 UTC, simskij requested changes

2021-07-23 12:19 UTC, simskij commented on README.md
> +  })
Singular form of `Queue`

2021-07-23 12:19 UTC, simskij commented on queues.go
> +}
Singular form of `Queue`

2021-07-23 12:19 UTC, simskij commented on exchanges.go
> +package amqp
Singular form of `Exchange`

2021-07-29 11:03 UTC, merged