Allow creating multiple connections and select which one to use
grafana/xk6-amqp pull request #27
Opened 2023-05-16 15:35 UTC by swantzter

fixes #24

2023-05-16 15:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/xk6-amqp?pullRequest=27) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/xk6-amqp?pullRequest=27) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/xk6-amqp?pullRequest=27) it.</sub>

2023-05-16 15:39 UTC, swantzter commented
I tried to keep this non-breaking which in some cases resulted in an added positional argument that takes an options struct, but relies on existing options structs if they exist.

2023-07-18 17:10 UTC, javaducky requested changes
Please rebase as this has merge conflicts given merge of #26 .

2023-07-31 12:37 UTC, swantzter commented
@javaducky sorry for the delay, I was enjoying a vacation away from a proper computer :) think it should be sorted now

2023-07-31 22:29 UTC, javaducky commented
@swantzter thank you! Looks like there are some linter issues related to missing documentation for the `*.GetConn` functions.

2023-07-31 22:39 UTC, swantzter commented
@javaducky yeah I was looking at them, but I can't see how what I've done differs from how the rest of the library code does it, do you have any pointers for how to align it?

2023-08-01 00:43 UTC, javaducky requested changes
With method documentation, the comment should begin with the actual name of the method/function itself.

2023-08-01 00:43 UTC, javaducky commented on amqp.go
> +// Gets an initialised connection by ID, or returns the last initialised one if ID is 0
```suggestion
// GetConn gets an initialised connection by ID, or returns the last initialised one if ID is 0
```

2023-08-01 00:43 UTC, javaducky commented on exchanges.go
> +// Gets an initialised connection by ID, or returns the last initialised one if ID is 0
``` suggestion
// GetConn gets an initialised connection by ID, or returns the last initialised one if ID is 0
```

2023-08-01 00:43 UTC, javaducky commented on queues.go
> +// Gets an initialised connection by ID, or returns the last initialised one if ID is 0
```suggestion
// GetConn gets an initialised connection by ID, or returns the last initialised one if ID is 0
```

2023-08-02 20:43 UTC, javaducky approved these changes
LGTM! Thank you for getting those updates!

2023-08-02 20:43 UTC, merged